config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  resources :orders
  resources :friendships
  resources :home


  get 'friends/index'
  get 'home/index'
  get 'friends/', to: 'friends#index'
  post 'userjoin/', to: 'orders#join'
  get 'groupfriends', to: 'groups#groupfriends'
  post 'remove_friend_from_group', to: 'groups#remove_friend_from_group'
  post 'add_friend_to_group', to: 'groups#add_friend_to_group'
  get 'userfriends', to: 'groups#userfriends'
  resources :notifications
  resources :user_notifications
  resources :items
  


  devise_for :users ,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  #authenticated :user do
    #root 'home#index', as: 'authenticated_root'
  #end
  resources :groups
  resources :users
  root to: "home#index"
  # devise_for :users,
  #          path: 'users'
  # delete 'logout', to: 'devise/sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  has_many :users
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    if current_user
    @notifications = Notification.all
  else
      redirect_to '/users/sign_in'
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:message, :from, :type, :orderId)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :notification_message %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from, id: :notification_from %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :notification_type %>
  </div>

  <div class="field">
    <%= form.label :orderId %>
    <%= form.number_field :orderId, id: :notification_orderId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>From</th>
      <th>Type</th>
      <th>Orderid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.message %></td>
        <td><%= notification.from %></td>
        <td><%= notification.type %></td>
        <td><%= notification.orderId %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<p>
  <strong>From:</strong>
  <%= @notification.from %>
</p>

<p>
  <strong>Type:</strong>
  <%= @notification.type %>
</p>

<p>
  <strong>Orderid:</strong>
  <%= @notification.orderId %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>