config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  resources :orders
  resources :friendships
  resources :home


  get 'friends/index'
  get 'home/index'
  get 'friends/', to: 'friends#index'
  post 'userjoin/', to: 'orders#join'
  get 'groupfriends', to: 'groups#groupfriends'
  post 'remove_friend_from_group', to: 'groups#remove_friend_from_group'
  post 'add_friend_to_group', to: 'groups#add_friend_to_group'
  get 'userfriends', to: 'groups#userfriends'
  resources :notifications
  resources :user_notifications
  resources :items
  


  devise_for :users ,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  #authenticated :user do
    #root 'home#index', as: 'authenticated_root'
  #end
  resources :groups
  resources :users
  root to: "home#index"
  # devise_for :users,
  #          path: 'users'
  # delete 'logout', to: 'devise/sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  def name_for_friends
    "#{User.find(friend_id).name}"
  end

  def image_for_friends
    "#{User.find(friend_id).image}"
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_action :set_friendship, only: [:show, :edit, :update]

  # GET /friendships
  # GET /friendships.json
  def index
    if current_user
        @friendships = Friendship.where(user_id: current_user.id)
      else
        	redirect_to '/users/sign_in'
        end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @searchFriend=User.find_by_email(params[:email])


    if @searchFriend == nil
      @friendship=nil
      respond_to do |format|
        format.html { redirect_to friendships_url, notice: 'Friend Not Found.' }
        format.json { render :show, status: :created, location: @friendship }
      end
    else

      @isFriendBefore=Friendship.where(user_id:current_user.id,friend_id:@searchFriend.id).exists?
      if @isFriendBefore !=false
        respond_to do |format|
          format.html { redirect_to friendships_url, notice: 'S/He is already Your Friend.' }
          format.json { render :show, status: :created, location: @friendship }
        end
      else
        @friendship = Friendship.new(user_id:current_user.id,friend_id:@searchFriend.id)
        respond_to do |format|
          if @friendship.save
            format.html { redirect_to friendships_url, notice: 'Friendship was successfully created.' }
            format.json { render :show, status: :created, location: @friendship }
          else
            format.html { render :new }
            format.json { render json: @friendship.errors, status: :unprocessable_entity }
          end
        end
      end
    end


  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    Friendship.where(friend_id:params[:id]).destroy_all
    # respond_to do |format|
    #   format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_friendship
    @friendship = Friendship.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<!--<input type="text" placeholder="Add Friend" id="FreindEmail"/>-->
<!--<%= link_to "New Task", friendships_path, id: "new_link" %>-->
<!--<div class="actions">-->
<!--<button id="addFriend">Add Friend</button>-->
<!--</div>-->

<%= form_with(model: @friendship) do |form| %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :friendship_email%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Friendships</h1>
<%= render 'form', friendship: @friendship %>
<table>
  <thead>
  <tr>
    <th>Friend</th>
    <th colspan="10"></th>
  </tr>
  </thead>

  <tbody>
  <% @friendships.each do |friendship| %>
    <tr>
      <!--<td><% friendship.user.name %></td>-->
      <td><img class ="friendImage" src="<%= friendship.friend.image %>"/> </td>
      <td><%= friendship.friend.name %></td>
      <td class="deleteFriend" to=<%= friendship.friend.id %> ><a>Remove</a></td>
      <!--<td><%= link_to 'Show', friendship %></td>-->
      <!--<td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>-->
      <!--<td><%= link_to 'Remove', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Friendship', new_friendship_path %>-->

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>